name = "Omelette"
uuid = "e52c2cb8-508e-4e12-9dd2-9c4755b60e73"
authors = ["odow <o.dowson@gmail.com>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
JuMP = "1"
julia = "1.6"
