name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
# needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # Since MathOptAI doesn't have binary dependencies, only test on a
        # subset of possible platforms.
        include:
          - version: '1'
            os: ubuntu-latest
            arch: x64
    env:
      JULIA_CONDAPKG_BACKEND: "Null"
      JULIA_PYTHONCALL_EXE: "python3"
    steps:
      - uses: actions/checkout@v4
      # Install pytorch
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install pytorch
        run: |
           pip3 install torch --index-url https://download.pytorch.org/whl/cpu
           pip3 install numpy
      # Install Julia
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v1
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
        with:
          depwarn: error
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4
        with:
          file: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
